### PR TITLE
Update nextcloud cron job

### PR DESCRIPTION
**Pull request by danb35**
Increase memory_limit to 512M.  See https://community.nethserver.org/t/php-increase-the-realt-value-to-the-memory/16222

### CODE REVIEW

**Comment by DavidePrincipi** [comment]
Thank you for the patch, Dan.

There's an issue in the build system and the RPM wasn't built.

I'm looking after it

image

Source https://travis-ci.com/github/NethServer/nethserver-nextcloud/requests

Edit: I asked for support from Travis-CI.com -- NethServer/dev#6249

**Review by stephdl — APPROVED** [review]

**Comment by stephdl** [comment]
man php says 

       --define foo[=bar]
       -d foo[=bar]   Define INI entry foo with value bar

would it be possible to get  `-d memory_limit=512M` instead of `-dmemory_limit=512M`

**Review by stephdl — COMMENTED** [review]
man php says 

       --define foo[=bar]
       -d foo[=bar]   Define INI entry foo with value bar

would it be possible to get  `-d memory_limit=512M` instead of `-dmemory_limit=512M`

To test your command 

`/usr/bin/scl enable rh-php73 -- php -d memory_limit=512M -r "phpinfo();"| | grep  memory_limit`

**Comment by danb35** [comment]
> would it be possible to get -d memory_limit=512M instead of -dmemory_limit=512M

Done.  Suggest updating the wiki page to match, as that's where this syntax came from.

**Comment by stephdl** [comment]
Thank dan for your quick job

**Comment by stephdl** [comment]
Even the code inside nethserver :D

```
/etc/e-smith/events/actions/nethserver-nextcloud-conf:8:    TERM=dumb runuser -s /bin/bash apache -c "php -dmemory_limit=512M ./occ $params"
/etc/e-smith/events/actions/nethserver-nextcloud-occ-conf:21:    system("TERM=dumb su - apache -s /bin/bash -c \"source /opt/rh/rh-php73/enable; cd /usr/share/nextcloud/; php -dmemory_limit=512M occ $params\"");
```

**Pull request merged**
