### PR TITLE
Remove the trailling / of the fpm unix socket

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/6339

### CODE REVIEW

**Review by DavidePrincipi — COMMENTED** [review]
Great patch! Let's wait @gsanchietti's

**Review by gsanchietti — COMMENTED** [review]
Did you test it?
If it works, feel free to merge it.

**Comment by stephdl** [comment]
yes it works with, but I think we could have a broken plugin one day, if you agree all I would like to do it and move to QA

**Comment by gsanchietti** [comment]
Fine

**Comment by stephdl** [comment]
so please approve it :D

**Review by gsanchietti — APPROVED** [review]

**Pull request merged**
