### PR TITLE
Spec: requires nextcloud 12.0.5

### PR DESCRIPTION
**Pull request by alepolidori**
**Description**
This is to upgrade to newer versione 12.0.5 which has many [bug fixes](https://nextcloud.com/changelog/).

**Other**
I've tested the upgrade from previous release 12.0.4 and all seems to work correctly.

NethServer/dev#5416

### CODE REVIEW

**Comment by udobes** [comment]
Today I did the update from 12.0.4 to 12.0.5 
and now I get a HTTP-500-Error.
What happend, can anyone help me?
Udo

P.S.
The problem is in that line of the .htaccess
RewriteBase https://mydomain.de/cloud/

Without that line, everything works obviosly well.

**Comment by gsanchietti** [comment]
> The problem is in that line of the .htaccess

@udobes is this a custom configuration for your installation?

**Comment by udobes** [comment]
> @udobes is this a custom configuration for your installation?

I haven't written that line, it comes however from the installation process?!
Udo

**Comment by udobes** [comment]
> @udobes is this a custom configuration for your installation?

I haven't written that line. It comes however from the installation process?!
Udo

**Pull request merged**
